### PR TITLE
Add Token-Based Authentication

### PR DESCRIPTION
**Pull request by boaf**
I'm not sure this is 100% ready to be merged yet (though I have tested thoroughly in my environment), but I just wanted to get the ball rolling on discussing the addition of TBA to these tools.

Thanks!

### CODE REVIEW

**Comment by ryanwinchester** [comment]
Looks good but I don't use tokens so can't test it.

**Comment by boaf** [comment]
Thanks for the response @ryanwinchester

Hmm, would you be able to enable TBA in your NS account, if only temporarily? (It's under Setup > SuiteCloud > Manage Authentication)

Otherwise, I'm not sure how best to go about testing this.

**Comment by dbrmr** [comment]
I can confirm, that this feature is working.

**Comment by ryanwinchester** [comment]
Thanks

**Comment by boaf** [comment]
Thanks for the confirmation @dbrmr and for the merge @ryanwinchester!

**Pull request merged**
