### PR TITLE
Generated 2018_2 classes

### PR DESCRIPTION
**Pull request by jrebs**
This is a simple update to master which includes classes extracted from the PHPToolkit 2018_2, which is the most recent available toolkit until 2019_1 gets released as a toolkit.

### CODE REVIEW

**Comment by ryanwinchester** [comment]
Thanks :)

**Comment by jrebs** [comment]
My pleasure, Ryan. Thanks for providing this package. I see you released the new version, but I am not getting it available through composer still. I can get it if I request dev-master, but otherwise it wants to grab 2017_1 still. What causes composer to see the new build?

**Comment by ryanwinchester** [comment]
Should be auto-updated. I see the latest tag on the right, so should work by now.

https://packagist.org/packages/ryanwinchester/netsuite-php

**Comment by jrebs** [comment]
You're right, Ryan, it's updated now. An hour ago I was still seeing 2017.1 on packagist.org.

**Pull request merged**
