### PR TITLE
Readme extension mention

### PR DESCRIPTION
**Pull request by 37ch4**
Just a quick mention to make sure the required extensions are enabled in php.ini for those not aware.

### CODE REVIEW

**Comment by ryanwinchester** [comment]
That is windows server-specific, though.

Also, [the requirements are listed in `composer.json`](https://github.com/ryanwinchester/netsuite-php/blob/master/composer.json#L13-L18)

```json
"require": {
    "php": ">=5.3.0",
    "ext-soap": "*",
    "ext-SimpleXML": "*",
    "ext-openssl": "*"
  }
```

Maybe we could just link to there from the readme?

**Comment by 37ch4** [comment]
I had to enable the soap extension on Manjaro Linux running php 7.

Yeah maybe more generic at the bottom. Maybe a small note or just links.

**Comment by 37ch4** [comment]
I think it could come after the composer include line just so you have instructions to follow. Possibly just an "If you run into errors make sure to check {link} or just state to check for those php extensions.

**Comment by ryanwinchester** [comment]
Thanks

**Pull request closed without merging**
