### PR TITLE
Add type hinting to exported classes

### PR DESCRIPTION
**Pull request by neclimdul**
Using this library has been great but navigating objects is also pretty time consuming and PHPStorm can't really help me out with completions because the classes from NetSuite don't have any hints so its been kinda slow trying to prototype and experiment with different services and having to dig through the object explorer and opening every class file.

The basic idea was that `$paramtypesmap` generally holds a definition of the types for each property of the class. This isn't actually useful to any IDE's though so it just sits there and you have to read each class to find out the properties. Most IDE's can read phpdoc style variable definitions though and provide inspection and completion based on it. So if we can take those definitions and convert them its a big developer experience win.

To do this, I used php's tokenizer to parse the class definition into a structured format we can look at. Then it digs through until it find the magic property, translates that into real types, and writes it back into the class string.

This ends up with a class that looks something like this:
```
class AsyncUpsertListRequest {
    /**
     * @var \NetSuite\Classes\Record[]
     */
    public $record;
    static $paramtypesmap = array(
        "record" => "Record[]",
    );
}
```

This is approach is very functional and should be pretty bullet proof and fast since the php tokenizer is very quick. However it is also _really_ ugly so let me know if there are any changes. So far copying them modified classes over to a project has made navigating the objects a _lot_ easier so I hope you like it. :-D

### CODE REVIEW

**Comment by jrebs** [comment]
Hi James, sorry for the lag getting to evaluating this PR, but it's been quite a year as I am sure we can all appreciate. :) I've tested out the changes and there seems to be a bit of a problem with the patch. I haven't bothered rooting out where it is because in my code editor I do get all the desired hinting and cross-referencing of the toolkit code (vscode using PHP Intelephense extension).

The issue I found when generating classes from the 2019_2 toolkit is that there are many occurrences of two docblocks preceding a property. Here are a couple examples:

`Account.php`
```php
    /**
     * @var \NetSuite\Classes\RecordRef
     */
    /**
     * @var \NetSuite\Classes\RecordRef
     */
    public $unitsType;
```
`AccountSearchBasic.php`
```php
    /**
     * @var \NetSuite\Classes\SearchMultiSelectField
     */
    /**
     * @var \NetSuite\Classes\SearchStringField
     */
    public $externalIdString;
```

**Comment by neclimdul** [comment]
Good catch! pushed a fix. The regex wasn't matching correctly. when it was adding the docblock for `$externalId` it was matching `$externalIdString` as well and so `$externalIdString` was getting the both doc blocks. I included the semicolon in the match so that doesn't happen and it seems to have fixed the problem.

**Comment by jrebs** [comment]
Thanks, James. Looks good, now.

**Comment by jrebs** [comment]
Just FYI I have tagged `v2019.2.1` today which incorporates the doctags. Thanks again.

**Pull request merged**
